// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Antd = require("antd");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

var $$Option = {};

function mockVal(str, repeatOpt, param) {
  var repeat = repeatOpt !== undefined ? repeatOpt : 1;
  return {
          value: str.repeat(repeat)
        };
}

function BasicAutoComplete(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var match$1 = React.useState(function () {
        return [];
      });
  var setOptions = match$1[1];
  var options = match$1[0];
  var onSearch = function (searchText) {
    console.log("searchText string", searchText);
    if (typeof searchText === "string") {
      Curry._1(setOptions, (function (param) {
              return [];
            }));
    } else {
      var options = [
        mockVal(searchText, undefined, undefined),
        mockVal(searchText, 2, undefined),
        mockVal(searchText, 3, undefined)
      ];
      Curry._1(setOptions, (function (param) {
              return options;
            }));
    }
    if (searchText === "") {
      var options$1 = [];
      return Curry._1(setOptions, (function (param) {
                    return options$1;
                  }));
    }
    var options$2 = [
      mockVal(searchText, undefined, undefined),
      mockVal(searchText, 2, undefined),
      mockVal(searchText, 3, undefined)
    ];
    return Curry._1(setOptions, (function (param) {
                  return options$2;
                }));
  };
  var onSelect = function (data, e) {
    console.log("onSelect", data, e.value);
    
  };
  var onChange = function (data) {
    console.log("onChange data", data);
    return Curry._1(setValue, (function (param) {
                  return data;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Antd.AutoComplete, {
                  options: options,
                  placeholder: "input here",
                  onSearch: onSearch,
                  onSelect: onSelect,
                  style: {
                    width: "200px"
                  }
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Antd.AutoComplete, {
                  options: options,
                  placeholder: "control mode",
                  value: match[0],
                  onChange: onChange,
                  onSearch: onSearch,
                  onSelect: onSelect,
                  style: {
                    width: "200px"
                  }
                }));
}

var make = BasicAutoComplete;

var $$default = BasicAutoComplete;

exports.$$Option = $$Option;
exports.mockVal = mockVal;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* antd Not a pure module */
