// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function number(v) {
  return v;
}

function string(v) {
  return v;
}

var DefaultOptionTypeValue = {
  number: number,
  string: string
};

function dataSourceItemObject(v) {
  return v;
}

function reactNode(v) {
  return v;
}

var DataSourceItemType = {
  dataSourceItemObject: dataSourceItemObject,
  reactNode: reactNode
};

exports.DefaultOptionTypeValue = DefaultOptionTypeValue;
exports.DataSourceItemType = DataSourceItemType;
/* No side effect */
